ТЗ 14
kurbatovik/java-shareit pull request #5
Opened 2023-04-26 16:18 UTC by kurbatovik

2023-04-27 08:17 UTC, afomkina requested changes
Хорошая работа, молодец 🔥 
Не пугайся такому количеству комментариев, очень многие направлены на саморазвитие и изучение дополнительной информации. Если будет что-то непонятно по ревью, можно подсветить здесь эти моменты с помощью комментариев или написать мне в пачку

2023-04-27 08:17 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<BookingDto> createBooking(@RequestHeader("X-Sharer-User-Id") @Positive Long userId,
Нужно вынести повторяющийся хэдер в отдельный класс, например,`Variables` и сделать его публичной константой. Так мы избежим множественного дублирование одной и той же строки по всему коду

2023-04-27 08:17 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private BookingState getState(String state) {
Нужно перенести в `enum BookingState`, так как эта часть логики относится к нему

2023-04-27 08:17 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-04-27 08:17 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ALL:
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2023-04-27 08:17 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ALL:
И здесь тоже помогут паттерны

2023-04-27 08:17 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
>   * TODO Sprint add-bookings.
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-04-27 08:17 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
Использование `@Data` в jpa-сущностях приводит к [вот этой проблеме](https://habr.com/ru/company/haulmont/blog/564682/)

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +        return CommentDto.builder().id(c.getId()).text(c.getText()).authorName(c.getAuthor().getName())
Для лучшей читаемости в коммерческой разработке принято бить билдеры по строкам:
```suggestion
        return CommentDto.builder()
            .id(c.getId())
            .text(c.getText())
            .authorName(c.getAuthor().getName())
```

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Enumerated(EnumType.STRING)
👍

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private LocalDateTime end;
Для полей с датой можно добавить [@JsonFormat](https://www.baeldung.com/spring-boot-formatting-json-dates)

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/config/ServerH2Configuration.java
> +public class ServerH2Configuration {
Лишняя конфигурация. Для старта и работы приложения она не нужна. Нужно удалить

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    String text;
У полей не хватает модификатора доступа

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
Нужно избавиться от `@Data` в jpa сущностях

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/resources/Schema.sql
> +CREATE TABLE IF NOT EXISTS users (
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +import javax.persistence.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public Function<Booking, BookingDto> getToDto() {
Метод нигде не используется, нужно использовать или удалить

2023-04-27 08:17 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("User with id: {0} not have available", userId);
Повторяющееся сообщение об ошибке лучше сделать константой

2023-04-29 03:25 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ALL:
Спасибо, за дополнительный материал, для меня это очень ценно. Сейчас у меня совсем нет времени, дедлайн очень близко. Взял на карандаш, обязательно изучу.

2023-04-29 03:26 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ALL:
✍️

2023-04-29 03:33 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<BookingDto> createBooking(@RequestHeader("X-Sharer-User-Id") @Positive Long userId,
☑️

2023-04-29 03:33 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private BookingState getState(String state) {
☑️

2023-04-29 03:34 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
☑️

2023-04-29 03:34 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
☑️

2023-04-29 03:35 UTC, kurbatovik commented on src/main/resources/Schema.sql
> +CREATE TABLE IF NOT EXISTS users (
☑️

2023-04-29 03:35 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +import javax.persistence.*;
☑️

2023-04-29 03:35 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    public Function<Booking, BookingDto> getToDto() {
☑️

2023-04-29 03:35 UTC, kurbatovik commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            throw new NotFoundException("User with id: {0} not have available", userId);
☑️

2023-04-30 07:57 UTC, AnastasiyaFomkina approved these changes

2023-04-30 08:27 UTC, merged